# Generated by Django 4.0 on 2022-06-17 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_dni_user_is_change_password_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
