# Generated by Django 4.0 on 2022-06-20 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='image',
            new_name='image_page',
        ),
    ]
